### ISSUE TITLE
Plugin showing "No supported modules were found. Try refreshing external projects" error

### ISSUE THREAD

**Issue by sivaprasadreddy** [JetBrains/package-search-intellij-plugin#118]
I am using IntelliJ IDEA 2023.3.4 (Ultimate Edition) Build #IU-233.14475.28.
I have installed the latest Package Search plugin (233.11800.6) and opened a multi-module maven project.
When I open Package Search Tool window, it shows "No supported modules were found. Try refreshing external projects" error. Nothing happens even after clicking Refresh.

**Comment by lamba92** [comment]
Hi thank you for the report! Do you have a test project on which we can test on?

**Comment by Nasller** [comment]
This problem is very easy to reproduce on maven package manager，many official source libraries are not working
For example. https://github.com/netty/netty.git or https://github.com/alibaba/canal.git
