### ISSUE TITLE
Phantom appears when dragging the window

### ISSUE THREAD

**Issue by Nasller** [JetBrains/package-search-intellij-plugin#131]
https://github.com/seata/seata

The entire tool window is damaged

![image](https://github.com/JetBrains/package-search-intellij-plugin/assets/26132153/e1d0f1cc-6184-403c-b576-ab8b64ed22c0)

**Comment by lamba92** [comment]
Hi, can you please give additional details about the version of Package search you are using, IDEA version and OS?

**Comment by Nasller** [comment]
win11 IDEA version is 2023.3.4. Open and drag to reproduce this issue

**Comment by lamba92** [comment]
Fix incoming, see https://github.com/JetBrains/package-search-intellij-plugin/pull/138

**Comment by Nasller** [comment]
thanks

**Comment by Nasller** [comment]
This has been fixed, so closed
